name: bot
version: 0.22.3-dev
author: Kevin Moore <kevin@thinkpixellab.com>
description: A collection of (mostly) general libraries to make working with Dart more productive.
homepage: https://github.com/kevmoo/bot.dart
documentation: http://kevmoo.github.io/bot.dart
environment:
  sdk: '>=0.6.5'
dependencies:
  meta: '>=0.6.5'
  unittest: '>=0.6.5'
dev_dependencies:
  browser: '>=0.6.5'
  hop: '>=0.24.0'
  html5lib: '>=0.4.4'
  path: '>=0.6.5'
  serialization: '>=0.6.5'
